name: web

on:
  push:
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - "package.json"
      - "tsconfig.base.json"
      - "docker-compose.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run lint --workspace apps/web
      - run: npm run build --workspace apps/web

  deploy:
    if: github.ref == 'refs/heads/main' && secrets.WEB_ECR_URI != ''
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build web container
        run: |
          docker build \
            -f apps/web/Dockerfile \
            -t ${{ secrets.WEB_ECR_URI }}:${{ github.sha }} \
            .
      - name: Push image
        run: docker push ${{ secrets.WEB_ECR_URI }}:${{ github.sha }}
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.WEB_ECS_CLUSTER }} \
            --service ${{ secrets.WEB_ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
      - name: Tag image as latest (optional)
        if: ${{ always() && secrets.WEB_ECR_URI != '' }}
        run: |
          docker tag ${{ secrets.WEB_ECR_URI }}:${{ github.sha }} ${{ secrets.WEB_ECR_URI }}:latest
          docker push ${{ secrets.WEB_ECR_URI }}:latest
